spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/thealthdb
    username: admin
    password: admin
  flyway:
    locations: classpath:db.migration

otp:
  props:
    attempts-threshold: 5
    interval: "PT1M"
